#!/usr/bin/env node
// Reads and writes the generated architecture summary in a pull request
// description. The summary lives between two marker lines; everything outside
// them is written by people and is never touched.
//
//   node pr-section.mjs extract <outfile>   current summary (empty if none)
//   node pr-section.mjs publish <infile>    replace or append the summary
//
// Environment: GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER, HEAD_SHA, RUN_URL.

import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

export const OPEN_MARKER = "<!-- architecture-summary -->";
export const CLOSE_MARKER = "<!-- /architecture-summary -->";

// GitHub rejects descriptions over 65,536 characters. Leave room for the
// human-written part to keep growing.
const MAX_BODY = 64000;

// A marker only counts alone on its own line, so prose that mentions the
// marker in backticks is never mistaken for it. \r? tolerates CRLF bodies
// saved from the web editor.
const OPEN_RE = /^<!-- architecture-summary -->[ \t]*\r?$/m;
const CLOSE_RE = /^<!-- \/architecture-summary -->[ \t]*\r?$/m;

/** Returns the summary text between the markers, or "" when there is none. */
export function extractSection(body) {
  const range = findSection(body ?? "");
  return range ? body.slice(range.contentStart, range.contentEnd).trim() : "";
}

/**
 * Returns `body` with the summary replaced by `section`, wrapped in a
 * collapsed block that names the commit it describes. Appends the summary
 * when the description has no markers yet.
 */
export function spliceSection(body, section, { headSha, runUrl }) {
  const current = body ?? "";
  const block = [
    OPEN_MARKER,
    "<details>",
    "<summary><strong>Architecture summary</strong></summary>",
    "",
    `_Generated by Claude for ${headSha.slice(0, 7)}. Rewritten on every push; edits inside this block are overwritten. [Run log](${runUrl})_`,
    "",
    section.trim(),
    "",
    "</details>",
    CLOSE_MARKER,
  ].join("\n");

  const range = findSection(current);
  const next = range
    ? current.slice(0, range.start) + block + current.slice(range.end)
    : `${current.trimEnd()}${current.trim() ? "\n\n" : ""}${block}\n`;

  if (next.length > MAX_BODY) {
    throw new Error(
      `Description would be ${next.length} characters, over the ${MAX_BODY} limit.`,
    );
  }
  return next;
}

function findSection(body) {
  const open = OPEN_RE.exec(body);
  if (!open) return null;
  const afterOpen = open.index + open[0].length;
  const close = CLOSE_RE.exec(body.slice(afterOpen));
  if (!close) return null;
  const closeIndex = afterOpen + close.index;
  return {
    start: open.index,
    contentStart: afterOpen,
    contentEnd: closeIndex,
    end: closeIndex + close[0].length,
  };
}

async function main([command, path]) {
  if (command === "extract" && path) {
    const pr = await github("GET");
    writeFileSync(path, extractSection(pr.body));
    return;
  }
  if (command === "publish" && path) {
    const section = readFileSync(path, "utf8");
    if (!section.trim())
      throw new Error("Refusing to publish an empty summary.");
    const pr = await github("GET");
    const body = spliceSection(pr.body, section, {
      headSha: env("HEAD_SHA"),
      runUrl: env("RUN_URL"),
    });
    if (body !== pr.body) await github("PATCH", { body });
    return;
  }
  throw new Error("Usage: pr-section.mjs extract <outfile> | publish <infile>");
}

async function github(method, payload) {
  const url = `https://api.github.com/repos/${env("GITHUB_REPOSITORY")}/pulls/${env("PR_NUMBER")}`;
  const response = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${env("GITHUB_TOKEN")}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: payload ? JSON.stringify(payload) : undefined,
  });
  if (!response.ok) {
    throw new Error(`${method} ${url} failed: ${response.status}`);
  }
  return response.json();
}

function env(name) {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable ${name}`);
  return value;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
