import { describe, expect, it } from "vitest";
import {
  CLOSE_MARKER,
  OPEN_MARKER,
  extractSection,
  spliceSection,
} from "@/.github/scripts/pr-section.mjs";

const meta = {
  headSha: "abcdef1234567890",
  runUrl: "https://github.com/o/r/actions/runs/1",
};

describe("spliceSection", () => {
  it("appends a summary to a description without markers", () => {
    const body = spliceSection(
      "## Summary\n- Adds a page",
      "What it is.",
      meta,
    );
    expect(body.startsWith("## Summary\n- Adds a page\n\n")).toBe(true);
    expect(body).toContain(OPEN_MARKER);
    expect(body).toContain("Generated by Claude for abcdef1.");
    expect(extractSection(body)).toContain("What it is.");
  });

  it("handles an empty description", () => {
    const body = spliceSection(null, "What it is.", meta);
    expect(body.startsWith(OPEN_MARKER)).toBe(true);
  });

  it("replaces only the text between the markers", () => {
    const first = spliceSection("Intro", "Old summary.", meta);
    const withTail = `${first}\nTrailing note`;
    const next = spliceSection(withTail, "New summary.", meta);
    expect(next.startsWith("Intro\n\n")).toBe(true);
    expect(next.endsWith("\nTrailing note")).toBe(true);
    expect(next).not.toContain("Old summary.");
    expect(next.match(new RegExp(OPEN_MARKER, "g"))).toHaveLength(1);
  });

  it("ignores markers mentioned mid-line", () => {
    const body = `The bot writes between \`${OPEN_MARKER}\` and \`${CLOSE_MARKER}\`.`;
    expect(extractSection(body)).toBe("");
    const next = spliceSection(body, "Summary.", meta);
    expect(next.startsWith(body)).toBe(true);
  });

  it("matches markers saved with CRLF line endings", () => {
    const body = `Intro\r\n${OPEN_MARKER}\r\nold\r\n${CLOSE_MARKER}\r\n`;
    const next = spliceSection(body, "New.", meta);
    expect(next).not.toContain("old");
    expect(next.match(new RegExp(OPEN_MARKER, "g"))).toHaveLength(1);
  });

  it("refuses to exceed GitHub's description limit", () => {
    expect(() => spliceSection("x".repeat(64000), "Summary.", meta)).toThrow(
      /limit/,
    );
  });
});
